<?php
$cfg['modules'] = [
    'category' => [
        'search',
        'add',
        'mod',
        'del',
        'view',
        'set_schedule',
        'acl_add',
        'acl_del',
        'non_working_days_add',
        'non_working_days_del',
    ],
    'user' => [
        'login',
        'search',
        'add',
        'mod',
        'del',
        'view',
        'set_all',
        'acl_add',
        'acl_del',
        'print_in_school',
        'set_schedule',
        'non_working_days_add',
        'non_working_days_mod',
        'non_working_days_del',
    ],
    'rfid' => [
        'search',
        'add',
        'mod',
        'del',
    ],
    'user_absence' => [
        'search',
        'add',
        'mod',
        'del',
    ],
    'cc_supplier' => [
        'search',
        'add',
        'mod',
        'view',
        'del',
    ],
    'cc_product' => [
        'search',
        'add',
        'mod',
        'view',
        'del',
    ],
    'cc_purchase' => [
        'search',
        'add',
        'mod',
        'view',
        'del',
        'set_status',
    ],
    'cc_delivery' => [
        'search',
        'add',
        'mod',
        'view',
        'del',
        'undel',
    ],
    'cc_help' => [
        'view',
    ],
    'error' => [
        'search',
    ],
];